rootProject.name = 'java-study'

include 'chapter01-generics-collections'
include 'chapter02-hashmap-lru'
include 'chapter03-sorting-trees'
include 'chapter04-functional-interface'
include 'chapter05-stream-optional'
include 'chapter06-modern-java-syntax'
include 'chapter07-jvm-memory-model'
include 'chapter08-object-model'
include 'chapter09-reflection-annotations'
include 'chapter10-thread-basics'
include 'chapter11-executor-blocking-queue'
